featurizer:
  name: PhysicochemicalFeaturizer

model:
  type: GenerativeLightningModule
  architecture:
    name: VAE
    params:
      input_dim: 10 # PhysicochemicalFeaturizer outputs 10 features
      latent_dim: 5
      encoder_hidden_dims: [32]
      decoder_hidden_dims: [32]
  lightning_module_params:
    optimizer_params:
      lr: 0.0001
    scheduler_params:
      name: StepLR
      step_size: 10
      gamma: 0.1
    kl_weight: 0.1 # Increased KL weight further for stability

trainer:
  max_epochs: 10
  accelerator: "auto"
  devices: 1
  logger_name: generative_vae_physicochemical
  log_dir: ./lightning_logs
  monitor_gradients: False
  gradient_clip_val: 1.0
  
