featurizer:
  name: PhysicochemicalFeaturizer # Or any featurizer that outputs fixed-size embeddings

model:
  type: screening
  architecture:
    name: TransformerEncoder
    params:
      embedding_dim: 10 # This should match the featurizer output dimension
      num_heads: 2
      num_layers: 1
      dim_feedforward: 32
  lightning_module_params:
    task_type: classification
    output_dim: 1
    optimizer_params:
      lr: 0.001
    scheduler_params:
      name: StepLR
      step_size: 10
      gamma: 0.1

trainer:
  max_epochs: 10
  logger_name: screening_transformer_physicochemical
  log_dir: ./lightning_logs
  monitor_gradients: True
  batch_size: 8
