name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install ruff mypy pytest pandas mlflow tensorboard
    - name: Run Ruff (Linting and Formatting)
      run: ruff check $(find . -name "*.py") --fix --config configs/quality/ruff.toml
    - name: Run MyPy (Static Type Checking)
      run: mypy --config-file configs/quality/mypy.ini src/
    - name: Run Pytest (Unit Tests)
      run: pytest
